// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktuvfjygrzrkyjaijwoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dXZmanlncnpya3lqYWlqd295Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2OTExOTEsImV4cCI6MjA2MTI2NzE5MX0.MD_7oWyN_v43luxNeuBOLmoswNS5XK28GwedxvrUbHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);